In [ ]:
!pip install konlpy
!pip install koreanize-matplotlib
!pip install wordcloud

In [3]:
import numpy as np
import pandas as pd

In [31]:
# 출력을 소수점 이하 3자리로 제한
%precision 3

# DataFrame 의 출력을 소수점 이하 3자리로 제한
#pd.set_option("display.precision", 3)

'%.3f'

In [32]:
df = pd.read_csv('/content/ch2_scores_em.csv')
df.head()

student number  english  mathematics
0               1       42           65
1               2       69           80
2               3       56           63
3               4       41           63
4               5       57           76

In [33]:
scores = np.array(df['english'])[:10]
scores 

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58])

In [34]:
scores_df = pd.DataFrame({'score' : scores},
                         index = pd.Index(['A', 'B', 'C', 'D', 'E', 
                                           'F', 'G', 'H', 'I', 'J'],
                                          name = 'student'))
scores_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

In [35]:
sum(scores) / len(scores)

55.0

In [36]:
np.mean(scores) # 평균

55.0

In [37]:
scores_df.mean()

score    55.0
dtype: float64

In [38]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69])

In [39]:
n = len(sorted_scores)
if n % 2 == 0:
  m0 = sorted_scores[n//2 - 1]
  m1 = sorted_scores[n//2]
  median = (m0 + m1) / 2
else:
  median = sorted_scores[(n+1)//2 - 1]

median

56.5

In [ ]:
np.median(scores) # 중앙값
scores

In [43]:
mean = np.mean(scores)
deviation = scores - mean

In [44]:
deviation # 편차

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [45]:
another_scores = [50, 60, 58, 54, 51, 56, 57, 53, 52, 59]
another_mean = np.mean(another_scores)
another_deviation = another_scores - another_mean
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [46]:
np.mean(deviation) # 편차의 평균

0.0

In [47]:
np.mean(another_deviation) 

0.0

In [48]:
summary_df = scores_df.copy()
summary_df['deviation'] = deviation
summary_df

score  deviation
student                  
A           42      -13.0
B           69       14.0
C           56        1.0
D           41      -14.0
E           57        2.0
F           48       -7.0
G           65       10.0
H           49       -6.0
I           65       10.0
J           58        3.0

In [50]:
summary_df.mean()

score        55.0
deviation     0.0
dtype: float64

In [ ]:
np.var(scores) == np.mean(deviation ** 2) # 분산

In [51]:
summary_df['square of deviation'] = np.square(deviation)
summary_df

score  deviation  square of deviation
student                                       
A           42      -13.0                169.0
B           69       14.0                196.0
C           56        1.0                  1.0
D           41      -14.0                196.0
E           57        2.0                  4.0
F           48       -7.0                 49.0
G           65       10.0                100.0
H           49       -6.0                 36.0
I           65       10.0                100.0
J           58        3.0                  9.0

In [52]:
summary_df.mean()

score                  55.0
deviation               0.0
square of deviation    86.0
dtype: float64

In [58]:
np.sqrt(np.var(scores, ddof = 0))

9.273618495495704

In [59]:
np.std(scores, ddof = 0)

9.273618495495704

In [60]:
z = (scores - np.mean(scores)) / np.std(scores)
z

array([-1.402,  1.51 ,  0.108, -1.51 ,  0.216, -0.755,  1.078, -0.647,
        1.078,  0.323])

In [61]:
np.mean(z), np.std(z, ddof = 0)

(-1.6653345369377347e-17, 0.9999999999999999)