Tensar operation & mainpulation in torch

In [38]:
import torch
import numpy as np

Initializing Tensar

In [2]:
torch.cuda.is_available() # cuda는 gpu를 의미함 -> gpu를 사용 가능하냐고 물어보는 함수

True

In [26]:
device = "cuda" if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [8]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [136]:
my_tensor = torch.tensor([[1,2,3],
                          [4,5,6],],
                          dtype = torch.float32,
                          device = device,
                          requires_grad = True)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)

In [13]:
torch.empty(size = (4,3,3)) # ->2차원 3차원이면 -> (3,3,3) -

tensor([[[2.1715e-18, 3.4305e-06, 5.3978e-05],
         [1.6691e+22, 2.1296e+23, 5.3936e-05],
         [1.6806e-04, 4.2284e+21, 6.4466e-10]],

        [[6.7194e-07, 1.4580e-19, 1.1495e+24],
         [3.0881e+29, 1.5766e-19, 1.8889e+31],
         [7.2065e+31, 2.8404e+29, 2.3089e-12]],

        [[1.9421e+31, 2.7491e+20, 6.1949e-04],
         [1.9421e+31, 2.7491e+20, 2.3078e-12],
         [7.1760e+22, 7.2250e+28, 1.5766e-19]],

        [[2.1629e+23, 1.0617e+21, 8.3553e+20],
         [2.1068e-07, 8.5409e+20, 6.7378e-10],
         [5.4371e+22, 2.6225e-09, 2.3052e-12]]])

In [14]:
torch.zeros((3,3)) # 다영으로 만들어 줌

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.rand((3,3)) # unifrom distribution에서 램덤으로 수를 뽑아서 배열을 만들어줌

tensor([[0.6209, 0.2313, 0.5595],
        [0.0121, 0.7545, 0.2652],
        [0.1954, 0.1440, 0.0356]])

In [17]:
torch.ones((3,3)) # 1로 채워진 함수

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch.eye(5,5) # 아이덴티티 메트릭스이다

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
torch.arange(5) # 레인지 수

tensor([0, 1, 2, 3, 4])

In [20]:
torch.arange(0,5,2) # 슬라이싱과 비슷 (시작값, 종료값, 스텝)

tensor([0, 2, 4])

In [21]:
torch.linspace(0.1,1,3) # 0.1부터 1까지 3등분한다

tensor([0.1000, 0.5500, 1.0000])

In [23]:
torch.empty(size = (2,2,3))

tensor([[[-6.8852e+23,  4.5856e-41, -6.8852e+23],
         [ 4.5856e-41,  4.4842e-44,  0.0000e+00]],

        [[ 1.1210e-43,  0.0000e+00,  5.7236e-34],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [31]:
my_tensor = torch.tensor([[[1,2,2],
                          [1,2,3]],
                         [[1,2,3],
                          [1,2,4]],],
                          dtype = torch.float32,
                          device = device,
                          requires_grad = True)
my_tensor

tensor([[[1., 2., 2.],
         [1., 2., 3.]],

        [[1., 2., 3.],
         [1., 2., 4.]]], device='cuda:0', requires_grad=True)

In [33]:
tensor = torch.arange(4)

In [35]:
print(tensor)
print(tensor.dtype)

tensor([0, 1, 2, 3])
torch.int64


In [36]:
print(tensor.bool())
print(tensor.short())
print(tensor.long())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])


In [37]:
tensor.float()

tensor([0., 1., 2., 3.])

In [49]:
np_arr = np.zeros((5,5))

In [50]:
tensor = torch.from_numpy(np_arr)

In [51]:
np_arr2 = tensor.numpy()
print(tensor)
print(type(tensor))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
<class 'torch.Tensor'>


In [53]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

In [54]:
z1 = torch.add(x,y)
z2 = x+y

print(z1)
print(z2)

tensor([5, 7, 9])
tensor([5, 7, 9])


In [55]:
z3 = x -y
print(z3)

tensor([-3, -3, -3])


In [56]:
z4 = torch.true_divide(x,y)
z5 = x /y
print(z5)

tensor([0.2500, 0.4000, 0.5000])


In [57]:
z6 = x / 2
print(z6) # broadcasting

tensor([0.5000, 1.0000, 1.5000])


In [58]:
t = torch.zeros(3)
print(t)
print(t.add(x))

tensor([0., 0., 0.])
tensor([1., 2., 3.])


In [59]:
t.add_(x) # "_()" 이면 원본데이터를 바꿈
t

tensor([1., 2., 3.])

In [60]:
x ** 2


tensor([1, 4, 9])

In [61]:
# MAtrix Multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

In [62]:
x3 = torch.mm(x1,x2) # mm()은 행렬의 곱 함수
print(x3)

tensor([[0.6387, 0.4353, 0.5652],
        [0.6073, 0.4959, 0.8262]])


In [63]:
x1.mm(x2)

tensor([[0.6387, 0.4353, 0.5652],
        [0.6073, 0.4959, 0.8262]])

In [64]:
x1 * 3

tensor([[0.1394, 1.2448, 1.4412, 0.1326, 0.7253],
        [0.4197, 1.3696, 0.1204, 1.5186, 0.9342]])

In [66]:
x - torch.tensor([1,2,3])
y = torch.tensor([1,2,3])

z = x * y # 인덱스끼리 곱
z

tensor([1, 4, 9])

In [67]:
torch.dot(x,y) # 내적값

tensor(14)

In [71]:
# batch mm
batch = 32
n = 10
m = 20
p = 30

t1 = torch.rand((batch, n, m))
t2 = torch.rand((batch, m, p))

result = torch.bmm(t1, t2)
print(result.shape) # 배치는 (배치, 행, 열)



torch.Size([32, 10, 30])


other opreations

In [72]:
x = torch.tensor([1,2,3])

In [73]:
torch.sum(x)

tensor(6)

In [74]:
z = torch.tensor([[1,2,3],
                  [4,5,6]])
z.shape

torch.Size([2, 3])

In [76]:
torch.sum(z, dim = 0) # dim = 0 은 열 방향 세로 방향을 다 더한 후 1차원 배열을 만든다 1은 행 가로 방형으로 다 더한 후 1차원 배열로 나옴

tensor([5, 7, 9])

In [82]:
torch.max(torch.tensor([1,2,3]), dim = 0) # 여기서의 dim은 벨류를 주고 거기의 인덱스를 같이 준다.

torch.return_types.max(
values=tensor(3),
indices=tensor(2))

In [83]:
x = torch.tensor([1,2,3])
value, index = torch.max(x, dim = 0)
print(value) # 최대값은 3
print(index) # 최대값의 인덱스의 위치는 2

tensor(3)
tensor(2)


In [85]:
torch.argmax(x, dim = 0) # argmax -> 최대값의 인덱스를 출력함

tensor(2)

In [86]:
torch.mean(x.float()) # mean은 float 이기에 .float()을 같이 사용해야함

tensor(2.)

In [87]:
torch.eq(x,y)

tensor([True, True, True])

Tenser Indexing

In [88]:
x

tensor([1, 2, 3])

In [91]:
print(x[1])
print(x[:2])

tensor(2)
tensor([1, 2])


In [92]:
z

tensor([[1, 2, 3],
        [4, 5, 6]])

In [93]:
print(z[0])

tensor([1, 2, 3])


In [97]:
print(z[1,1])
print(z[1, : ])

tensor(5)
tensor([4, 5, 6])


In [98]:
print(z[:, : ])

tensor([[1, 2, 3],
        [4, 5, 6]])


In [101]:
x = torch.arange(10)
indices = [2,5,8]

print(x[indices])

tensor([2, 5, 8])


In [102]:
x.ndimension() # ndimension 배열의 차원

1

In [103]:
torch.where(x > 5, x, x**2) # where (조건, 참이면, 거짓이면) -> 출력

tensor([ 0,  1,  4,  9, 16, 25,  6,  7,  8,  9])

  Tensor Reshaping -
  reshape()
  view()

In [105]:
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [110]:
x.reshape(3,4) # (n,m)으로 n x m 행렬로 재배치한다 (x,y,z)로도 가능

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [111]:
x.view(3,4) # reshape 과 비슷

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [112]:
x.view(2,-1) # -1의 의미는 자동으로 맞춰줌 예) 12 = n * m으로 m을 자동으로 만들어줌

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [113]:
batch = 64
x = torch.rand((batch, 2, 5))
print(x.shape)

torch.Size([64, 2, 5])


In [115]:
x.view(batch, -1).shape

torch.Size([64, 10])

In [116]:
x.shape

torch.Size([64, 2, 5])

In [117]:
z = x.permute(0,2,1) # (벨류0, 벨류2, 벨류1)로 재배치
z.shape

torch.Size([64, 5, 2])

베치를 재배치하는 이유는 재배치하기 위해

In [118]:
x = torch.arange(10)
x.shape

torch.Size([10])

In [119]:
x.unsqueeze(0).shape # 1자리의 차원을 추가한다 -> x는 1차원이였지만 unsqueeze를 해서 2차원이 되었다

torch.Size([1, 10])

In [120]:
x.unsqueeze(1).shape

torch.Size([10, 1])

In [124]:
t = torch.arange(10).unsqueeze(0).unsqueeze(1)
t.shape

torch.Size([1, 1, 10])

In [131]:
t.squeeze(1).shape

torch.Size([1, 10])

In [132]:
x1 = torch.rand(2,5)
x2 = torch.rand(2,5)

In [134]:
torch.cat((x1,x2), dim = 0).shape # 데이터를 합친다

torch.Size([4, 5])